apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: producer
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
