apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.serviceAccount.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }}
    {{- end }}
